```{r input, include=FALSE, echo=FALSE}
# Generate Markdown repport over clinically relevant variants and possible haplotype
#  with clinical guidelines.

## AUTHOR: Joel Ås
## MAIL: joel.as@medsci.uu.se
library(rmdformats)
library(tidyverse)
library(knitr)
library(kableExtra)
source("Ploty_coverage_plot.R")


# Input
args <- commandArgs(TRUE)
parseArgs <- function(x) strsplit(sub("^--", "", x), "=")
argsDF <- as.data.frame(do.call("rbind", parseArgs(args)))
argsL <- as.list(as.character(argsDF$V2))
names(argsL) <- argsDF$V1

detected_variants <- read.csv(argsL$found_variants, sep = "\t", stringsAsFactors = F, row.names = NULL)
missed_variants <- read.csv(argsL$missed_variants, sep = "\t", stringsAsFactors = F,  row.names = NULL)
haplotype_definitions <- read.csv(argsL$haplotype_definitions, sep = "\t", stringsAsFactors = F,  row.names = NULL)
clinical_guidelines <- read.csv(argsL$clinical_guidelines, sep = "\t", stringsAsFactors = F,  row.names = NULL)

# Formating
risk_duplication <- function(x){
  min_dup_var <- min(abs(c(1/4, 1/3, 2/3, 3/4) - x))
  min_diploid <- min(abs(c(0, 1) - x))
  if (min_dup_var > min_diploid){
    return(FALSE)
  }
  return(TRUE)
}
# Functions
get_haplotypes <- function(ID, haplotype_definitions=haplotype_definitions) {
  haplo <- haplotype_definitions[haplotype_definitions$ID == ID, "HAPLOTYPE"]
  return(paste(haplo, collapse = "/"))
}

detected_variants$Zygosity <- sapply(detected_variants$GT, function(x){
   b <- sum(as.numeric(strsplit(x, "[/|]", perl=T)[[1]]))
   return(c("Hetero-", "Homo-")[b])
})
risk_haplotypes <- array()
if (nrow(detected_variants) != 0) {
  detected_variants <- detected_variants %>% separate("AD", c("Ref.reads", "Alt.reads"), ",", remove=F)
  detected_variants[, "Ref.reads"] <- as.numeric(detected_variants[, "Ref.reads"])
  detected_variants[, "Alt.reads"] <- as.numeric(detected_variants[, "Alt.reads"])
  detected_variants$Haplotype <-
    sapply(detected_variants$ID, function(x) get_haplotypes(x, haplotype_definitions))

  columns <- c("GENE", "ID", "Haplotype", "Zygosity",  "Ref.reads", "Alt.reads", "GQ")
  verbose_columns <- c("Gen", "rsID", "Möjliga Haplotyper", "Zygositet",
                       "Ref Reads", "Alt Reads", "GQ")
  detected_variants_present <- detected_variants[, columns]
  colnames(detected_variants_present) <- verbose_columns
  detected_variants_present[, "Variantfrekvens"] <- detected_variants_present[, "Alt Reads"]/(detected_variants_present[, "Alt Reads"] + detected_variants_present[, "Ref Reads"])
  detected_variants_present[, "Möjlig Duplikation"] <- sapply(detected_variants_present[, "Variantfrekvens"], risk_duplication)
  faulty_haplotypes <-
          detected_variants_present[detected_variants_present[, "Möjlig Duplikation"] == TRUE, "Möjliga Haplotyper"]

  faulty_haplotypes <- unique(unlist(sapply(faulty_haplotypes, function(x) strsplit(x, "/"))))

} else {
  faulty_haplotypes <- array()
}
```

---
title: "`r argsL$title`"
date: "Date compiled: `r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output_format:
    html_document:
        toc: True
        theme: "readthedown"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Kliniska rekommendationer baserad på genotyper
```{r}
clin_columns <- c("gene", "Haplotype1", "Haplotype2", "Guideline")
verbose_columns <- c("Gen", "Haplotyp 1", "Haplotyp 2", "Klinisk Rekommendation")
clinical_guidelines_present <- clinical_guidelines[, clin_columns]
colnames(clinical_guidelines_present) <- verbose_columns

warning_idx <- which(clinical_guidelines_present[, "Haplotyp 1"] %in% faulty_haplotypes | clinical_guidelines_present[, "Haplotyp 2"] %in% faulty_haplotypes)

clinical_guidelines_present %>%
    kable(format = "html", escape = F) %>%
    kable_styling() %>%
    row_spec(warning_idx, bold=T, color ="white", background = "red")

```

```{r results="asis"}
if (length(warning_idx) != 0){
  cat("<b><u>En eller flera varianter som tillhör haplotyp har flagats som osäker.\n Följ inte rödmarkerade kliniska rekommendationer! </u></b>")
}

```


# Kliniskt relevanta varianter upptäckta
```{r detected_variants}
if (nrow(detected_variants) != 0 ){
  detected_variants_present %>%
    kable() %>%
    kable_styling() %>%
    row_spec(which(detected_variants_present[, "Möjlig Duplikation"] == T), bold=T, color="white", background="red")
}
``` 

# Läsdjup vid vildtyp kliniska targets
```{r coverage_wildtype}
columns <- c("ID", "Haplotype", "Locus", "Total_Depth")
missed_variants$Haplotype <-
  sapply(missed_variants$ID, function(x) get_haplotypes(x, haplotype_definitions))
missed_variants <- missed_variants[, columns]
colnames(missed_variants) <- c("rsID", "Haplotyp", "Position", "Läsjup")
missed_variants %>%
  kable() %>% 
  kable_styling() %>%
  row_spec(which(missed_variants[, "Läsjup"] < 100), bold=T, color ="white", background = "red")
```


# Läsdjup vid vid targets
```{r}
bait_table_file <- paste0(
    argsL$data_location,
    "/genomic_regions/exons_variants_pharmacogenomics_18_06_2019_ex_cyp2d6.bed"
    )
genes <- read.table(bait_table_file, sep = "\t", as.is=T, check.names = F,
                           col.names = c("Chr", "Start", "End", "Name")) %>%
    separate(Name, c("Target", "Gene"), "_") %>% {unique(.$Gene)}
plt  <- htmltools::tagList()
i    <- 0
for (gene in genes){
  i <- i + 1
  exon_table_file <- paste0(argsL$data_location, "/exons/", gene,".csv")
  target_table_file <- paste0(argsL$data_location, "/genomic_regions/target_rsid.bed")
  gdf_file <- argsL$depth_file

  plt[[i]] <- as_widget(get_ploty_depth_plot(
    argsL$found_variants,
    target_table_file,
    bait_table_file,
    gdf_file,
    exon_table_file,
    gene))
}
```

```{r}
plt
```